// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mvnpdf
arma::vec mvnpdf(arma::mat x, arma::rowvec mu, arma::mat sigma);
RcppExport SEXP _GibbsFlow_mvnpdf(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnpdf(x, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// mvnpdf_chol
arma::vec mvnpdf_chol(arma::mat x, arma::rowvec mu, arma::mat rooti, double rootisum);
RcppExport SEXP _GibbsFlow_mvnpdf_chol(SEXP xSEXP, SEXP muSEXP, SEXP rootiSEXP, SEXP rootisumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rooti(rootiSEXP);
    Rcpp::traits::input_parameter< double >::type rootisum(rootisumSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnpdf_chol(x, mu, rooti, rootisum));
    return rcpp_result_gen;
END_RCPP
}
// mvnrnd
arma::mat mvnrnd(int n, arma::rowvec mu, arma::mat sigma);
RcppExport SEXP _GibbsFlow_mvnrnd(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnrnd(n, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// systematic_resampling
arma::vec systematic_resampling(const arma::vec& normweights, int nparticles, double uniform);
RcppExport SEXP _GibbsFlow_systematic_resampling(SEXP normweightsSEXP, SEXP nparticlesSEXP, SEXP uniformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type normweights(normweightsSEXP);
    Rcpp::traits::input_parameter< int >::type nparticles(nparticlesSEXP);
    Rcpp::traits::input_parameter< double >::type uniform(uniformSEXP);
    rcpp_result_gen = Rcpp::wrap(systematic_resampling(normweights, nparticles, uniform));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GibbsFlow_mvnpdf", (DL_FUNC) &_GibbsFlow_mvnpdf, 3},
    {"_GibbsFlow_mvnpdf_chol", (DL_FUNC) &_GibbsFlow_mvnpdf_chol, 4},
    {"_GibbsFlow_mvnrnd", (DL_FUNC) &_GibbsFlow_mvnrnd, 3},
    {"_GibbsFlow_systematic_resampling", (DL_FUNC) &_GibbsFlow_systematic_resampling, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_GibbsFlow(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
