# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname gaussian_logprior
#' @title Evaluate multivariate Gaussian prior density
#' @param x evaluation points  
#' @return density values
#' @export
gaussian_logprior <- function(x) {
    .Call('_GibbsFlow_gaussian_logprior', PACKAGE = 'GibbsFlow', x)
}

#' @rdname gaussian_gradlogprior
#' @title Evaluate gradient of multivariate Gaussian prior density
#' @param x evaluation points  
#' @return gradient values
#' @export
gaussian_gradlogprior <- function(x) {
    .Call('_GibbsFlow_gaussian_gradlogprior', PACKAGE = 'GibbsFlow', x)
}

#' @rdname gaussian_partialderivative_logprior
#' @title Evaluate partial derivative of multivariate Gaussian prior density
#' @param dim dimension along which partial derivative is taken (dim = 0 is the first coordinate)
#' @param x evaluation points  
#' @return partial derivative values
#' @export
gaussian_partialderivative_logprior <- function(dim, x) {
    .Call('_GibbsFlow_gaussian_partialderivative_logprior', PACKAGE = 'GibbsFlow', dim, x)
}

#' @rdname gaussian_sampleprior
#' @title Sample from multivariate Gaussian prior distribution
#' @param n number of samples 
#' @return samples 
#' @export
gaussian_sampleprior <- function(n) {
    .Call('_GibbsFlow_gaussian_sampleprior', PACKAGE = 'GibbsFlow', n)
}

#' @rdname gaussian_loglikelihood
#' @title Evaluate multivariate Gaussian loglikelihood function
#' @param x evaluation points  
#' @return density values
#' @export
gaussian_loglikelihood <- function(x) {
    .Call('_GibbsFlow_gaussian_loglikelihood', PACKAGE = 'GibbsFlow', x)
}

#' @rdname gaussian_gradloglikelihood
#' @title Evaluate gradient of multivariate Gaussian likelihood function
#' @param x evaluation points  
#' @return gradient values
#' @export
gaussian_gradloglikelihood <- function(x) {
    .Call('_GibbsFlow_gaussian_gradloglikelihood', PACKAGE = 'GibbsFlow', x)
}

#' @rdname gaussian_partialderivative_loglikelihood
#' @title Evaluate partial derivative of multivariate Gaussian likelihood function
#' @param dim dimension along which partial derivative is taken (dim = 0 is the first coordinate)
#' @param x evaluation points  
#' @return partial derivative values
#' @export
gaussian_partialderivative_loglikelihood <- function(dim, x) {
    .Call('_GibbsFlow_gaussian_partialderivative_loglikelihood', PACKAGE = 'GibbsFlow', dim, x)
}

#' @rdname gaussian_posterior_cov
#' @title Compute posterior covariance of multivariate Gaussian example
#' @param lambda temperature
#' @return posterior covariance
#' @export
gaussian_posterior_cov <- function(lambda) {
    .Call('_GibbsFlow_gaussian_posterior_cov', PACKAGE = 'GibbsFlow', lambda)
}

#' @rdname gaussian_posterior_mean
#' @title Compute posterior mean of multivariate Gaussian example
#' @param lambda temperature
#' @return posterior mean
#' @export
gaussian_posterior_mean <- function(lambda) {
    .Call('_GibbsFlow_gaussian_posterior_mean', PACKAGE = 'GibbsFlow', lambda)
}

#' @rdname gaussian_log_normconst
#' @title Compute log normalizing constant of multivariate Gaussian example
#' @param lambda temperature
#' @return log normalizing constant
#' @export
gaussian_log_normconst <- function(lambda) {
    .Call('_GibbsFlow_gaussian_log_normconst', PACKAGE = 'GibbsFlow', lambda)
}

#' @rdname gaussian_logposterior
#' @title Evaluate multivariate Gaussian posterior density
#' @param x evaluation points  
#' @param lambda temperature
#' @return density values
#' @export
gaussian_logposterior <- function(x, lambda) {
    .Call('_GibbsFlow_gaussian_logposterior', PACKAGE = 'GibbsFlow', x, lambda)
}

#' @rdname gaussian_gibbsflow
#' @title Compute Gibbs flow for Gaussian model
#' @param stepsize numerical integration step size
#' @param lambda tempering level
#' @param derivative_lambda time derivative of tempering schedule
#' @param xparticles particle locations
#' @param logdensity corresponding log density values 
#' @return list with keys: 
#' \code{xparticles} new particle locations,
#' \code{log_jacobian_dets} log Jacobian determinant of the flow
#' @export
gaussian_gibbsflow <- function(stepsize, lambda, derivative_lambda, xparticles, logdensity) {
    .Call('_GibbsFlow_gaussian_gibbsflow', PACKAGE = 'GibbsFlow', stepsize, lambda, derivative_lambda, xparticles, logdensity)
}

#' @rdname mvnpdf
#' @title Evaluate multivariate Gaussian density
#' @param x evaluation points  
#' @param mu mean vector  
#' @param sigma covariance matrix
#' @return density values
#' @export
mvnpdf <- function(x, mu, sigma) {
    .Call('_GibbsFlow_mvnpdf', PACKAGE = 'GibbsFlow', x, mu, sigma)
}

#' @rdname mvnpdf_chol
#' @title Evaluate multivariate Gaussian density (with pre-computed Cholesky factor)
#' @param x evaluation points  
#' @param mu mean vector  
#' @param rooti inverse of Cholesky factor
#' @param rootisum normalizing constant term
#' @return density values
#' @export
mvnpdf_chol <- function(x, mu, rooti, rootisum) {
    .Call('_GibbsFlow_mvnpdf_chol', PACKAGE = 'GibbsFlow', x, mu, rooti, rootisum)
}

#' @rdname mvnrnd
#' @title Simulate from multivariate Gaussian distribution
#' @param n number of samples
#' @param mu mean vector  
#' @param sigma covariance matrix
#' @return samples 
#' @export
mvnrnd <- function(n, mu, sigma) {
    .Call('_GibbsFlow_mvnrnd', PACKAGE = 'GibbsFlow', n, mu, sigma)
}

#' @rdname systematic_resampling
#' @title Perform systematic resampling
#' @param normweights normalized particle weights 
#' @param nparticles number of particles
#' @param uniform uniform variable between 0 to 1 / nparticles 
#' @return \code{ancestors} ancestor indices
#' @export
systematic_resampling <- function(normweights, nparticles, uniform) {
    .Call('_GibbsFlow_systematic_resampling', PACKAGE = 'GibbsFlow', normweights, nparticles, uniform)
}

