# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname mvnpdf
#' @title Evaluate multivariate Gaussian density
#' @param x evaluation points  
#' @param mu mean vector  
#' @param sigma covariance matrix
#' @return density values
#' @export
mvnpdf <- function(x, mu, sigma) {
    .Call('_GibbsFlow_mvnpdf', PACKAGE = 'GibbsFlow', x, mu, sigma)
}

#' @rdname mvnpdf_chol
#' @title Evaluate multivariate Gaussian density (with pre-computed Cholesky factor)
#' @param x evaluation points  
#' @param mu mean vector  
#' @param rooti inverse of Cholesky factor
#' @param rootisum normalizing constant term
#' @return density values
#' @export
mvnpdf_chol <- function(x, mu, rooti, rootisum) {
    .Call('_GibbsFlow_mvnpdf_chol', PACKAGE = 'GibbsFlow', x, mu, rooti, rootisum)
}

#' @rdname mvnrnd
#' @title Simulate from multivariate Gaussian distribution
#' @param n number of samples
#' @param mu mean vector  
#' @param sigma covariance matrix
#' @return samples 
#' @export
mvnrnd <- function(n, mu, sigma) {
    .Call('_GibbsFlow_mvnrnd', PACKAGE = 'GibbsFlow', n, mu, sigma)
}

#' @rdname systematic_resampling
#' @title Perform systematic resampling
#' @param normweights normalized particle weights 
#' @param nparticles number of particles
#' @param uniform uniform variable between 0 to 1 / nparticles 
#' @return \code{ancestors} ancestor indices
#' @export
systematic_resampling <- function(normweights, nparticles, uniform) {
    .Call('_GibbsFlow_systematic_resampling', PACKAGE = 'GibbsFlow', normweights, nparticles, uniform)
}

